name: samsara
description: Some utilities about Flutter & Flame.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.32.0
  flame_splash_screen: ^0.3.0
  flame_audio: ^2.11.7
  logger: ^2.5.0

  hetu_script:
    path: ../hetu-script/packages/hetu_script
  hetu_script_flutter:
    path: ../hetu-script/packages/hetu_script_flutter
  fluent_ui:
    path: ../fluent_ui
  llama_cpp_dart:
    path: ../llama_cpp_dart

  html: ^0.15.1
  vector_math: ^2.1.4
  path_provider: ^2.0.13
  path: ^1.8.2
  flutter_platform_alert: ^0.8.0
  colorfilter_generator: ^0.0.8
  meta: ^1.10.0
  quiver: ^3.2.1
  flutter_custom_cursor: ^0.0.4
  image: ^4.5.2
  animated_tree_view: ^2.3.0
  flutter_markdown_plus: ^1.0.5
  provider: ^6.1.5+1
  gpt_markdown: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
